framework: mocha
preRun:
  command:
    - yarn install
preMerge:
  pattern: ['app/**/*.spec.ts', 'app/**/*.tests.js', 'app/**/*.tests.ts', 'server/**/*.tests.ts', 'ee/**/*.tests.ts']
postMerge:
  pattern: ['app/**/*.spec.ts', 'app/**/*.tests.js', 'app/**/*.tests.ts', 'server/**/*.tests.ts', 'ee/**/*.tests.ts']
postRun:
  command:
    - node --version
configFile: .mocharc.js
version: 1.0
